### ISSUE TITLE
no any example is given about how to use this

### ISSUE THREAD

**Issue by aman4india** [YUNEEC/Yuneec-RTSP-Player-Android#3]
Check the main activity, its empty. please give some example about how to use those methods

**Comment by Sushma7785** [comment]
Hi Aman,

Please refer [this example](https://github.com/YUNEEC/Yuneec-SDK-Android-Example/blob/master/app/src/main/java/com/yuneec/example/component/fragment/CameraFragment.java), which demonstrates the use of this library. We will also add an example here soon. 

Thanks!

**Comment by aman4india** [comment]
Thank you. I got that.
