### ISSUE TITLE
Could not find codec parameters for stream 0 ...

### ISSUE THREAD

**Issue by wajdan846** [YUNEEC/Yuneec-RTSP-Player-Android#5]
Getting this error repeatedly:
```
Could not find codec parameters for stream 0 (Video: h264, 1 reference frame, none(left)): unspecified size Consider increasing the value for the 'analyzeduration' and 'probesize' options
```

here is my implementation

```
    private void initRtspPlayer(SurfaceView videoSurfaceView ) {
        videoSurfaceHolder = videoSurfaceView.getHolder();
        videoSurfaceHolder.addCallback(new SurfaceHolder.Callback() {
            @Override
            public void surfaceCreated(SurfaceHolder holder) {
                videoSurface = holder.getSurface();
                try {
                    videoPlayer.setSurface(videoSurface);
                } catch (VideoPlayerException e) {
                    e.printStackTrace();
                }
            }

            @Override
            public void surfaceChanged(SurfaceHolder holder, int format, int width, int height) {
                videoSurface = holder.getSurface();
                try {
                    videoPlayer.setSurface(videoSurface);
                    videoPlayer.start();
                } catch (VideoPlayerException e) {
                    e.printStackTrace();
                }
            }

            @Override
            public void surfaceDestroyed(SurfaceHolder holder) {
                try {
                    videoPlayer.setSurface(null);
                } catch (VideoPlayerException e) {
                    e.printStackTrace();
                }
            }
        });
    }

```

        ctype2 = (SurfaceView) findViewById(R.id.player);
        initRtspPlayer(ctype2);
        videoPlayer = (RTSPPlayer) VideoPlayer.getPlayer(VideoPlayer.PlayerType.LIVE_STREAM);
        videoPlayer.initializePlayer();
        try {
            videoPlayer.setDataSource("rtsp://admin:newtech148@testingcam.ddns.net:554");
            //videoPlayer.setDataSource("rtsp://184.72.239.149/vod/mp4:BigBuckBunny_175k.mov");
            videoPlayer.start();
        } catch (IOException e) {
            e.printStackTrace();
            Log.e("stream",e.toString());
        } catch (VideoPlayerException e) {
            e.printStackTrace();
            Log.e("stream",e.toString());
        }

**Comment by julianoes** [comment]
Thanks for reporting. When this happens, can you ignore the exception and continue? Or does everything crash at that point?

**Comment by wajdan846** [comment]
Thankyou for your response

No the app doesnot crash, yet I am facing a problem where the rtsp link works on my home network but always fails when multiple clients are connected in the same network i.e the live stream shows up on the player when in home (my device connected alone) and the stream doesnot show in the university.

The link works perfectly on VLC media player irrespective of the network it is in.

**Comment by julianoes** [comment]
Hm, ok. I don't think we have tried that. 

Since this is based on ijkplayer, have you looked for help there already?
https://github.com/Bilibili/ijkplayer/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+Could+not+find+codec+parameters+for+stream

**Comment by wajdan846** [comment]
this ssue hasnt been resolved there as well

**Comment by julianoes** [comment]
Hm ok, that means it's an issue in their player and not our example here, so I'm going to close that here.
Sorry about that.

**Comment by wajdan846** [comment]
Hey,

I just signed the petition "Office of the High Commissioner for Human
Rights: URGENT PETITION ON THE UN KASHMIR REPORT" and wanted to see if you
could help by adding your name.

Our goal is to reach 500,000 signatures and we need more support. You can
read more and sign the petition here:

http://chng.it/JKjsSTVMVV

Thanks!
Wajdan
